### ISSUE TITLE
Issue with integration between Rasa with slack

### ISSUE THREAD

**Issue by SivaLokam** [JustinaPetr/Weatherbot_Tutorial#38]
Hi,
Many thanks for the video and the code, It was really helpful
I used your code and able to run to execute as Rest server

When I want to integrate My bot with Slack,I tried using run.py (  from teh [Latest release of Rasa NLU and Rasa Core]

But When I run the file and see the console only below part is getting displayed 
![rasa](https://user-images.githubusercontent.com/20257905/46919754-7cac2000-d001-11e8-9031-7d53e8ac126b.jpg)

Can you help me with sample code to open Slack Channel and integrate my bot with slack

**Comment by vigneshp826** [comment]
@SivaLokam you might be interested in this discussion.

https://stackoverflow.com/questions/47068709/your-cpu-supports-instructions-that-this-tensorflow-binary-was-not-compiled-to-u

**Comment by JustinaPetr** [comment]
Hey @SivaLokam. That's all good. When you see this in your console, it means that the agent is loaded and is waiting for user messages which should be passed in through slack. Once you will send a message, you should see in your console that the Rasa Core server got a request with a message. The output message will also be sent back to slack rather than your console.

**Comment by SivaLokam** [comment]
@JustinaPetr ,Thanks for the reply,Yeah it was working and I integrated my bot with slack too 👍

**Comment by JustinaPetr** [comment]
Awesome! Glad to hear :)
