### ISSUE TITLE
Latest Directory missing train_init.py file

### ISSUE THREAD

**Issue by this-is-r-gaurav** [JustinaPetr/Weatherbot_Tutorial#46]

**Comment by JustinaPetr** [comment]
The latest version doesn't need train_init.py file anymore, that's why it's not included :) The instructions on how to run the interactive learning with the latest version are provided in a readme. The repo is not yet updated for Rasa Core v.0.12 which introduced a couple of new things, but I will do so later today.

**Comment by this-is-r-gaurav** [comment]
Oh Thank You, i thought it is missed by chance
